### ISSUE TITLE
Some Mobs HP is too low.

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilArcheology1.7#114]
For example, Triceratops HP is only 30. It's one of the largest herbivores, and it's doesn't even have twice the heath of the player. And the Dodo has less heath than the Compy! Here's my suggestions:

Triceratops: 60 HP
Tyrannosaurus: 87 HP
Stegosaurus: 52 HP
Dilophosaurus: 23 HP
Brachiosaurus: 136 HP
Spinosaurus: 90 HP
Ankylosaurus: 82 HP
Deinonychus: 20 HP
Pachycephalosaurus: 30 HP
Gallimimus: 33 HP
Allosaurus: 59 HP
Ceratosaurus: 42 HP
Smilodon: 23 HP
Elasmotherium: 36 HP
Plesiosaur: 41 HP
Mosasaurus: 67 HP
Dodo: 12 HP
Gastornis: 20 HP
Titanis: 22 HP
Phorusrhacos: 24 HP
Kelenken: 28 HP

**Comment by RunAndBite** [comment]
Goodness, can we also get the Deinonychus health to at least 20? I mean, why would a wolf have more health than a raptor that's nearly 1.5 times bigger? This has been bugging me since I knew their health stats. I mean, why, just why? Not to mention the fact that Deinonychus can't survive a creeper attack. How am I supposed to raise a Raptor army when creepers can kill multiple Raptors with one hit? :stuck_out_tongue:

**Comment by Adsper** [comment]
Added some more.

**Comment by Alex-the-666** [comment]
Fixed in 7.3
