### ISSUE TITLE
Map dont generate the fossils block

### ISSUE THREAD

**Issue by fenix2009** [FossilsArcheologyRevival/FossilArcheology1.7#164]
Hey i have already a map i did but the mod don´t generate the blocks randomly around the world why?

**Comment by 4f6f3b** [comment]
New blocks will only generate in undiscovered chunks. Generally mods will not generate new blocks in chunks you already explored.

**Comment by LiteraryRecluse** [comment]
Yep, when you add in a new mod the chunks you have already generated won't change, you will have to go further than you ever have to start generating blocks/items/ores in new biomes.  If you add mods into a world you already have generated it'll also cause biome edge glitches, where a new biome might be 20 blocks higher than the one beside it and cause a harsh edge with exposed cave and lava/water pouring out of it.

That's why it is usually good to have all your mods loaded in before you create a new world.  I'm the same way though, I tend to load mods in late and just deal with the hassle of having to discover new cave systems in new areas in order to experience them. *Shrug*

**Comment by fenix2009** [comment]
Yeh but i just found this mode yesterday

**Comment by fenix2009** [comment]
Dont exist any mode to generate randomly the block around the world
