### ISSUE TITLE
palaeoraphe trees leaves die

### ISSUE THREAD

**Issue by ShawZam** [FossilsArcheologyRevival/FossilArcheology1.7#215]
immediately after planting a palaeoraphe tree the leaves begin to de-spawn and so i cant plant furns 7.2.1

**Comment by zenieldanaku** [comment]
I think that happens because the palaeoraphe logs are not recognized as wood. If you put, for example, jungle wood adyacent to the palaeoraphe leaves, they don't de-spawn. Simmilary, I tryed to make charcoal out of palaeoraphe wood, but the furnace did nothing. That's because, I think, the logs are not recognized as "wood".

**Comment by 4f6f3b** [comment]
https://github.com/FossilsArcheologyRevival/FossilArcheology1.7/issues/193

**Comment by zenieldanaku** [comment]
good. Now I'll wait for the build. Happy new year!
